---

version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'ready for review'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'ready for review'
