on:
  issue_comment:
    types:
      - created
jobs:
  distgen-check:
    uses: "sclorg/ci-actions/.github/workflows/distgen-check.yml@main"
  check-readme:
    uses: "sclorg/ci-actions/.github/workflows/check-readme.yml@main"
  container-tests:
    uses: "sclorg/ci-actions/.github/workflows/container-tests.yml@main"
    with:
      enabled-tests: '["container","container-pytest","openshift-pytest","container-fips"]'
      versions: '[ "22", "22-minimal", "24", "24-minimal", "26", "26-minimal" ]'
      openshift-versions: '[ "22", "22-minimal", "24", "24-minimal", "26", "26-minimal" ]'
    secrets: inherit
