on:
  issue_comment:
    types:
      - created
jobs:
  openshift-tests:
    # This job only runs for '[test-all]' or '[test-openshift] pull request comments by owner, member
    name: "${{ matrix.test_case }}tests: ${{ matrix.version }} - ${{ matrix.os_test }}"
    runs-on: ubuntu-20.04
    concurrency:
      group: ocp-${{ github.event.issue.number }}-${{ matrix.version }}-${{ matrix.os_test }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        version: [ "14", "14-minimal", "16", "16-minimal", "18", "18-minimal", "20", "20-minimal" ]
        os_test: [ "rhel7", "rhel8", "rhel9"]
        test_case: [ "openshift-4" ]

    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test-openshift]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - uses: sclorg/tfaga-wrapper@main
        with:
          os_test: ${{ matrix.os_test }}
          version: ${{ matrix.version }}
          test_case: ${{ matrix.test_case }}
          public_api_key: ${{ secrets.TF_PUBLIC_API_KEY }}
          private_api_key: ${{ secrets.TF_INTERNAL_API_KEY }}
